pub fn criteria_card_strings() -> Vec<String> {
    let mut vec_criteria_cards: Vec<String> = vec![];
    
    vec_criteria_cards.push(String::from("the Blue number compared to 3: \n I:    Blue < 3; \n II:   Blue == 3; \n III:  Blue > 3;"));
    vec_criteria_cards.push(String::from("the Blue number compared to 1: \n I:    Blue == 1; \n II:   Blue > 1;"));
    vec_criteria_cards.push(String::from("the Yellow number compared to 3: \n I:    Yellow < 3; \n II:   Yellow == 3; \n III:  Yellow > 3;"));
    vec_criteria_cards.push(String::from("the Yellow number compared to 4: \n I:    Yellow < 4; \n II:   Yellow == 4; \n III:  Yellow > 4;"));
    vec_criteria_cards.push(String::from("if Blue is even or odd: \n I:    Blue is even; \n II:   Blue is odd;"));
    vec_criteria_cards.push(String::from("if Yellow is even or odd: \n I:    Yellow is even; \n II:   Yellow is odd;"));
    vec_criteria_cards.push(String::from("if Purple is even or odd: \n I:    Purple is even; \n II:   Purple is odd;"));
    vec_criteria_cards.push(String::from("the number of 1's in the code: \n I:    zero 1's; \n II:   one 1; \n III:  two 1's; \n IV:   three 1's;"));
    vec_criteria_cards.push(String::from("the number of 3's in the code: \n I:    zero 3's; \n II:   one 3; \n III:  two 3's; \n IV:   three 3's;"));
    vec_criteria_cards.push(String::from("the number of 4's in the code: \n I:    zero 4's; \n II:   one 4; \n III:  two 4's; \n IV:   three 4's;"));
    vec_criteria_cards.push(String::from("the Blue number compared to the Yellow number: \n I:    Blue < Yellow; \n II:   Blue == Yellow; \n III:  Blue > Yellow;"));
    vec_criteria_cards.push(String::from("the Blue number compared to the Purple number: \n I:    Blue < Purple; \n II:   Blue == Purple; \n III:  Blue > Purple;"));
    vec_criteria_cards.push(String::from("the Yellow number compared to the Purple number: \n I:    Yellow < Purple; \n II:   Yellow == Purple; \n III:  Yellow > Purple;"));
    vec_criteria_cards.push(String::from("which color's number is smaller than either of the others: \n I:    Blue < Yellow && Blue < Purple; \n II:   Yellow < Blue && Yellow < Purple; \n III:  Purple < Blue && Purple < Yellow;"));
    vec_criteria_cards.push(String::from("which color's number is larger than either of the others: \n I:    Blue > Yellow && Blue > Purple; \n II:   Yellow > Blue && Yellow > Purple; \n III:  Purple > Blue && Purple > Yellow;"));
    vec_criteria_cards.push(String::from("the number of even numbers compared to the number of odd numbers: \n I:    even > odd; \n II:   even < odd;"));
    vec_criteria_cards.push(String::from("how many even numbers there are in the code: \n II:   one even number; \n III:  two even numbers; \n IV:   three even numbers;"));
    vec_criteria_cards.push(String::from("if the sum of all the numbers is even or odd: \n I:    Blue + Yellow + Purple == even; \n II:   Blue + Yellow + Purple == odd;"));
    vec_criteria_cards.push(String::from("the sum of Blue and Yellow compared to 6: \n I:    Blue + Yellow < 6; \n II:   Blue + Yellow == 6; \n III:  Blue + Yellow > 6;"));
    vec_criteria_cards.push(String::from("if a number repeats itself in the code: \n I:    a triple number; \n II:   a double number; \n III:  no repetition;"));
    vec_criteria_cards.push(String::from("if there is a number present exactly twice: \n I:    no pairs || three of a kind; \n II:   a pair;"));
    vec_criteria_cards.push(String::from("if the three numbers in the code are in ascending order, descending order, or no order: \n I:    ascending order; \n II:   descending order; \n III:  no order;"));
    vec_criteria_cards.push(String::from("the sum of all numbers compared to 6: \n I:    Blue + Yellow + Purple < 6; \n II:   Blue + Yellow + Purple == 6; \n III:  Blue + Yellow + Purple > 6;"));
    vec_criteria_cards.push(String::from("if there is a sequence of ascending numbers: \n I:    three numbers in ascending order; \n II:   two numbers in ascending order; \n III:  no numbers in ascending order;"));
    vec_criteria_cards.push(String::from("if there is a sequence of ascending or descending numbers: \n I:    three numbers in ascending or descending order; \n II:   two numbers in ascending or descending order; \n III:  no numbers in ascending or descending order;"));
    vec_criteria_cards.push(String::from("that a specific color is less than 3: \n I:    Blue < 3; \n II:   Yellow < 3; \n III:  Purple < 3;"));
    vec_criteria_cards.push(String::from("that a specific color is less than 4: \n I:    Blue < 4; \n II:   Yellow < 4; \n III:  Purple < 4;"));
    vec_criteria_cards.push(String::from("that a specific color is equal to 1: \n I:    Blue == 1; \n II:   Yellow == 1; \n III:  Purple == 1;"));
    vec_criteria_cards.push(String::from("that a specific color is equal to 3: \n I:    Blue == 3; \n II:   Yellow == 3; \n III:  Purple == 3;"));
    vec_criteria_cards.push(String::from("that a specific color is equal to 4: \n I:    Blue == 4; \n II:   Yellow == 4; \n III:  Purple == 4;"));
    vec_criteria_cards.push(String::from("that a specific color is greater than 1: \n I:    Blue > 1; \n II:   Yellow > 1; \n III:  Purple > 1;"));
    vec_criteria_cards.push(String::from("that a specific color is greater than 3: \n I:    Blue > 3; \n II:   Yellow > 3; \n III:  Purple > 3;"));
    vec_criteria_cards.push(String::from("that a specific color is even or odd: \n I:    Blue is even; \n II:   Blue is odd; \n III:  Yellow is even; \n IV:   Yellow is odd; \n V:    Purple is even; \n VI:   Purple is odd;"));
    vec_criteria_cards.push(String::from("which color has the smallest number (or is tied for the smallest number): \n I:    Blue <= Yellow && Blue <= Purple; \n II:   Yellow <= Blue && Yellow <= Purple; \n III:  Purple <= Blue && Purple <= Yellow;"));
    vec_criteria_cards.push(String::from("which color has the largest number (or is tied for the largest number): \n I:    Blue >= Yellow && Blue >= Purple; \n II:   Yellow >= Blue && Yellow >= Purple; \n III:  Purple >= Blue && Purple >= Yellow;"));
    vec_criteria_cards.push(String::from("the sum of all the numbers is a multiple of 3 or 4 or 5: \n I:    Blue + Yellow + Purple % 3 == 0; \n II:   Blue + Yellow + Purple % 4 == 0; \n III:  Blue + Yellow + Purple % 5 == 0;"));
    vec_criteria_cards.push(String::from("the sum of two specific colors is equal to 4: \n I:    Blue + Yellow == 4; \n II:   Blue + Purple == 4; \n III:  Yellow + Purple == 4;"));
    vec_criteria_cards.push(String::from("the sum of two specific colors is equal to 6: \n I:    Blue == 1; \n II:   Blue > 1; \n III:  Yellow == 1; \n IV:   Yellow > 1; \n V:    Purple == 1; \n VI:   Purple > 1;"));
    vec_criteria_cards.push(String::from("the number of one specific color compared to 1: \n I:    Blue == 1; \n II:   Blue > 1; \n III:  Yellow == 1; \n IV:   Yellow > 1; \n V:    Purple == 1; \n VI:   Purple > 1;"));
    vec_criteria_cards.push(String::from("the number of one specific color compared to 3: \n I:    Blue < 3; \n II:   Blue == 3; \n III:  Blue > 3; \n IV:   Yellow < 3; \n V:    Yellow == 3; \n VI:   Yellow > 3; \n VII:  Purple < 3; \n VIII: Purple == 3; \n IX:   Purple > 3;"));
    vec_criteria_cards.push(String::from("the number of one specific color compared to 4: \n I:    Blue < 4; \n II:   Blue == 4; \n III:  Blue > 4; \n IV:   Yellow < 4; \n V:    Yellow == 4; \n VI:   Yellow > 4; \n VII:  Purple < 4; \n VIII: Purple == 4; \n IX:   Purple > 4;"));
    vec_criteria_cards.push(String::from("which color is the smallest or the largest: \n I:    Blue < Yellow && Blue < Purple; \n II:   Blue > Yellow && Blue > Purple; \n III:  Yellow < Blue && Yellow < Purple; \n IV:   Yellow > Blue && Yellow > Purple; \n V:    Purple < Blue && Purple < Yellow; \n VI:   Purple > Blue && Purple > Yellow;"));
    vec_criteria_cards.push(String::from("the Blue number compared to the number of another specific color: \n I:    Blue < Yellow; \n II:   Blue < Purple; \n III:  Blue == Yellow; \n IV:   Blue == Purple; \n V:    Blue > Yellow; \n VI:   Blue > Purple;"));
    vec_criteria_cards.push(String::from("the Yellow number compared to the number of another specific color: \n I:    Yellow < Blue; \n II:   Yellow < Purple; \n III:  Yellow == Blue; \n IV:   Yellow == Purple; \n V:    Yellow > Blue; \n VI:   Yellow > Purple;"));
    vec_criteria_cards.push(String::from("how many 1's or how many 3's there are in the code: \n I:    zero 1's; \n II:   zero 3's; \n III:  one 1; \n IV:   one 3; \n V:    two 1's; \n VI:   two 3's;"));
    vec_criteria_cards.push(String::from("how many 3's or how many 4's there are in the code: \n I:    zero 3's; \n II:   zero 4's; \n III:  one 3; \n IV:   one 4; \n V:    two 3's; \n VI:   two 4's;"));
    vec_criteria_cards.push(String::from("how many 1's or how many 4's there are in the code: \n I:    zero 1's; \n II:   zero 4's; \n III:  one 1; \n IV:   one 4; \n V:    two 1's; \n VI:   two 4's;"));
    vec_criteria_cards.push(String::from("one specific color compared to another specific color: \n I:    Blue < Yellow; \n II:   Blue == Yellow; \n III:  Blue > Yellow; \n IV:   Blue < Purple; \n V:    Blue == Purple; \n VI:   Blue > Purple; \n VII:  Yellow < Purple; \n VIII: Yellow == Purple; \n IX:   Yellow > Purple;"));

    return vec_criteria_cards;
}