#![allow(dead_code)]

use crate::game_logic::game_variants::*;
use rand::{rngs::ThreadRng, thread_rng, Rng};
use std::{
    collections::HashMap,
    io,
    ops::RangeInclusive,
};

#[derive(Debug)]
pub enum Gamemode {
    Classic,
    Extreme,
    Nightmare,
}

#[derive(Debug)]
pub enum Difficulty {
    Easy,
    Standard,
    Hard,
}

pub struct TuringCodeEval {
    // Structure to pair every individual Turing Code with an array of booleans as it is put through every Test on every Criteria Card. This is replacing the pre-calculated Punch Cards used for querying the Turing Machine's Verifier Cards.
    pub code: u32,
    pub checks: Vec<(u8, bool)>, // Vec<(criteria_card_number, pass_or_fail)>
}

#[derive(Clone, Default)]
pub struct Puzzle {
    // Struct to contain all of the necessary data for the Puzzle that is generated by the associated algorithm
    pub target_code: u32,
    pub tests: Vec<usize>,
}

#[allow(unused_assignments)]
pub fn set_game_parameters() -> (u32, u32, char, char, Gamemode, Difficulty, usize, bool) {
    // This entire function allows the user to set all of the parameters of the Puzzle that will be generated to play.
    // At the moment, only Classic Mode, Original-Parameters are supported.

    let mut min_digit: char;
    let mut max_digit: char;
    let mut code_length: u8;
    let mut min_code: u32 = 0;
    let mut max_code: u32 = 0;

    let mut og_tm_game: bool;
    // If the user sets this bool to 'true' using the "y" match arm, then we can skip inputs for min_digit, max_digit, code_length, min_code, and max_code.
    // Otherwise, we gather that information in the "n" match arm.
    loop {
        let mut input = String::new();
        println!("Are you trying to play a game of the Original \"Turing Machine\" board game? \"y\" or \"n\"");
        io::stdin()
            .read_line(&mut input)
            .expect("Failed to read line");
        match input.trim() {
            "y" => {
                og_tm_game = true;
                min_digit = '1';
                max_digit = '5';
                code_length = 3;
                min_code = 111;
                max_code = 555;
                break;
            }
            
            "n" => {
                og_tm_game = false;

                loop {
                    let mut input = String::new();

                    println!(
                        "↓ Please input the smallest digit character (In the original game, this is '1')."
                    );
                    io::stdin()
                        .read_line(&mut input)
                        .expect("Failed to read line");
                    min_digit = match input.trim() {
                        "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" => input.trim().chars().next().expect("empty input"),
                        _ => {
                            println!("Invalid smallest digit character \"{}\"", input.trim());
                            continue;
                        }
                    };

                    let mut input = String::new();
                    
                    println!("↓ Please input the largest digit character (In the original game, this is '5').");
                    io::stdin()
                        .read_line(&mut input)
                        .expect("Failed to read line");
                    max_digit = match input.trim() {
                        "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" => input.trim().chars().next().expect("empty input"),
                        _ => {
                            println!("Invalid largest digit character \"{}\"", input.trim());
                            continue;
                        }
                    };
                    if max_digit <= min_digit {
                        println!(
                            "Largest digit character must be greater than smallest digit character: {} <= {}",
                            max_digit, 
                            min_digit
                        );
                        continue;
                    }
                    break;
                }

                loop {
                    let mut input = String::new();
                    println!("↓ Please input the number of digits in the valid codes (In the original game, this is 3, resulting in codes ranging from 111 to 555, inclusive).");
                    io::stdin()
                        .read_line(&mut input)
                        .expect("Failed to read line");
                    code_length = match input.trim().parse() {
                        Ok(num) => num,
                        Err(_) => {
                            println!("Invalid code length entered \"{}\"", input.trim());
                            continue;
                        }
                    };
                    match code_length {
                        3 => break,
                        _ => {
                            println!("Chosen length not implemented \"{}\"", code_length);
                            continue;
                        }
                    }
                }

                for _ in 1..=code_length {
                    min_code *= 10;
                    min_code += min_digit.to_digit(10).unwrap();
                    max_code *= 10;
                    max_code += max_digit.to_digit(10).unwrap();
                }
            }
            _ => {
                println!("Invalid input \"{}\"", input.trim());
                continue;
            }
        }
    }

    let mode: Gamemode;
    loop {
        let mut input = String::new();
        println!("↓ Please input the gamemode setting; Your choices are \"Classic Mode\"(c), \"Extreme Mode\"(e), and \"Nightmare Mode\"(n).");
        io::stdin()
            .read_line(&mut input)
            .expect("Failed to read line");
        mode = match input.trim() {
            "c" => Gamemode::Classic,
            "e" => Gamemode::Extreme,
            "n" => Gamemode::Nightmare,
            _ => {
                println!("Invalid mode selection \"{}\"", input.trim());
                continue;
            }
        };
        break;
    }

    let difficulty: Difficulty;
    loop {
        let mut input = String::new();
        println!("↓ Please input the difficulty setting; Your choices are \"Easy\"(e), \"Standard\"(s), and \"Hard\"(h).");
        io::stdin()
            .read_line(&mut input)
            .expect("Failed to read line");
        difficulty = match input.trim() {
            "e" => Difficulty::Easy,
            "s" => Difficulty::Standard,
            "h" => Difficulty::Hard,
            _ => {
                println!("Invalid difficulty selection \"{}\"", input.trim());
                continue;
            }
        };
        break;
    }

    let test_amount: usize;
    loop {
        let mut input = String::new();
        println!("↓ Please input the number of sections on the machine that are assigned Criteria Verifiers (In the original game, this is from 4 to 6, inclusive)");
        io::stdin()
            .read_line(&mut input)
            .expect("Failed to read line");
        test_amount = match input.trim().parse() {
            Ok(num) => num,
            Err(_) => {
                println!("Invalid criteria test amount entered \"{}\"", input.trim());
                continue;
            }
        };
        break;
    }

    (
        min_code,
        max_code,
        min_digit,
        max_digit,
        mode,
        difficulty,
        test_amount,
        og_tm_game,
    )
}

pub fn is_valid_turing_code(
    min_code: u32,
    max_code: u32,
    min_digit: char,
    max_digit: char,
    test_code: u32,
) -> bool {
    (min_code..=max_code).contains(&test_code)
        && test_code
            .to_string()
            .chars()
            .all(|c| c >= min_digit && c <= max_digit)
}

pub fn generate_random_puzzle_code(code_length: u32, min_digit: char, max_digit: char) -> u32 {
    let mut target_code: u32 = 0;
    let mut rand_num: ThreadRng = thread_rng();
    for _ in 1..=code_length {
        target_code *= 10;
        target_code +=
        rand_num.gen_range(min_digit.to_digit(10).unwrap()..=max_digit.to_digit(10).unwrap()) as u32;
    }
    target_code
}


fn set_test_pool_range(
    og_tm_game: bool,
    last_index: usize,
    mode: &Gamemode,
    difficulty: &Difficulty,
    second_half_of_puzzle: bool,
) -> RangeInclusive<usize> {
    use Gamemode::*;
    use Difficulty::*;
    let test_pool: RangeInclusive<usize>;
    if og_tm_game {
        if !second_half_of_puzzle {
            test_pool = match (mode, difficulty) {
                (Classic, Easy) => 0..=49,
                (Classic, Standard) => 17..=62,
                (Classic, Hard) => 69..=last_index,
                (Extreme, Easy) => 29..=71,
                (Extreme, Standard) => 29..=71,
                (Extreme, Hard) => 63..=last_index,
                (Nightmare, Easy) => 29..=49,
                (Nightmare, Standard) => 18..=62,
                (Nightmare, Hard) => 66..=last_index,
            }
        } else {
            test_pool = match (mode, difficulty) {
                (Classic, Easy) => 0..=49,
                (Classic, Standard) => 0..=62,
                (Classic, Hard) => 0..=last_index,
                (Extreme, Easy) => 0..=71,
                (Extreme, Standard) => 0..=71,
                (Extreme, Hard) => 0..=last_index,
                (Nightmare, Easy) => 0..=49,
                (Nightmare, Standard) => 0..=62,
                (Nightmare, Hard) => 0..=last_index,
            }
        }
    } else {
        test_pool = 0..=last_index;
    }
    test_pool
}


pub fn generate_results_matrix(
    min_code: u32,
    max_code: u32,
    min_digit: char,
    max_digit: char,
    og_tm_game: bool,
) -> (Vec<TuringCodeEval>, Vec<HashMap<String, Vec<bool>>>, HashMap<String, Vec<String>>) {
    let codes: Vec<u32> = (min_code..=max_code).into_iter().filter(|code| is_valid_turing_code(min_code, max_code, min_digit, max_digit, *code)).collect();
    let mut results_matrix: Vec<TuringCodeEval> = vec![];
    let mut machine: Vec<HashMap<String, Vec<bool>>> = vec![];
    let mut cards: Vec<String> = vec![];

    if og_tm_game {
        for code in codes.iter() {
            results_matrix.push(
                og_tm_board_game::criteria_card_tests::populate_machine_feedback(*code, &mut machine),
            )
        }
        cards.extend(og_tm_board_game::criteria_card_strings::criteria_card_strings());
    }
    // else {
    //     for code in codes.iter() {
    //         match (min_code, max_code, min_digit, max_digit) {
    //             (111, 555, '1', '5') => results_matrix.push(len3_min1_max5::criteria_card_tests::populate_machine_feedback(*code, &mut machine)),
    //             _ => {}
    //         }
    //     }
    //     match (min_code, max_code, min_digit, max_digit) {
    //         (111, 555, '1', '5') => cards.extend(len3_min1_max5::criteria_card_strings::criteria_card_strings()),
    //         _ => {}
    //     }
    // }

    let mut cardmap: HashMap<String, Vec<String>> = HashMap::default();
    for i in 0..cards.len() {
        let c = &cards[i];
        let splits: Vec<&str> = c.split("\n").collect();
        let n: Vec<String> = splits[0..].iter().map(|s| s.to_string()).collect();
        cardmap.insert((i + 1).to_string(), n);
    }

    (results_matrix, machine, cardmap)
}



fn is_unique_solution(
    target_index: &usize,
    puzzle_tests: &Vec<usize>,
    matrix: &Vec<TuringCodeEval>,
) -> bool {
    // returns true if puzzle_tests argument is a unique set of true booleans among all of the codes.
    for (index, turing_code_result) in matrix.iter().enumerate() {
        let all_true = puzzle_tests
            .iter()
            .all(|&i| turing_code_result.checks.get(i).map_or(false, |&(_, b)| b));

        if all_true && &index != target_index {
            return false;
        }
    }
    true
}

fn generate_coupled_criteria(matrix: &Vec<TuringCodeEval>) -> Vec<Vec<bool>> {
    let mut vec_test_couplings: Vec<Vec<bool>> = vec![vec![false; matrix[0].checks.len()]; matrix[0].checks.len()];

    // returns a 2D array of Coupled Tests. A test is coupled to another test if for every possible Turing Code, the result of Test X matches the result of Test Y. 
    // By definition, this renders one of the tests superfluous; Test X should not be paired with Test Y in a valid Puzzle, and vice versa.
    // also declares if two tests are coupled if they lie on the same Criteria Card, so they could never validly appear together in a puzzle anyway.
    let is_coupled = |x: usize, y: usize| -> bool {
        matrix
            .iter()
            .all(|turing_result| turing_result.checks[x].1 == turing_result.checks[y].1)
    };

    for x in 0..matrix[0].checks.len() {
        for y in 0..matrix[0].checks.len() {
            if x != y && ((matrix[0].checks[x].0 == matrix[0].checks[y].0) || (is_coupled(x, y))) {
                vec_test_couplings[x][y] = true;
                vec_test_couplings[y][x] = true;
            }
        }
    }

    vec_test_couplings
}

fn generate_centralizing_test_list_whole_range(matrix: &Vec<TuringCodeEval>, test_amount: usize) -> Vec<bool> {
    // The purpose of this is to ensure that no Criteria Test renders any of the other Tests in the Puzzle superfluous.
    let mut vct: Vec<bool> = vec![false; matrix[0].checks.len()];

    for x in 0..matrix[0].checks.len() {
        let mut count = 0;
        for y in 0..matrix.len() {
            if matrix[y].checks[x].1 {
                count += 1;
            }
        }
        if count < test_amount {
            vct[x] = true;
        }
    }

    vct
}

pub fn generate_puzzle(
    code_length: usize,
    min_digit: char,
    max_digit: char,
    matrix: &Vec<TuringCodeEval>,
    mode: &Gamemode,
    difficulty: &Difficulty,
    test_amount: usize,
    og_tm_game: bool,
) -> Puzzle {
    let _valid_code_set: Vec<u32> = matrix.iter().map(|a| a.code).collect();
    let couplings: Vec<Vec<bool>> = generate_coupled_criteria(&matrix);
    let vct_whole_range: Vec<bool> = generate_centralizing_test_list_whole_range(&matrix, test_amount);
    let mut vct_whole_range_count = 0;
    for (i, _) in vct_whole_range.iter().enumerate().filter(|a| *a.1) {
        vct_whole_range_count += 1;
        println!(
            "Banned Test for uniqueness: Card {}/{}, Test {}/{};",
            matrix[0].checks[i].0,
            matrix[0].checks[matrix[0].checks.len() - 1].0,
            i,
            matrix[0].checks.len() - 1
        );
    }
    println!("Number of centralizing tests: {vct_whole_range_count}");
    let half_tests = match test_amount % 2 {
        0 => test_amount / 2,
        _ => (test_amount / 2) + 1,
    };
    let mut ranges: Vec<RangeInclusive<usize>> = (0..test_amount)
        .map(|_| 0..=1)
        .collect();
    for i in 0..test_amount {
        ranges[i] = set_test_pool_range(
            og_tm_game,
            matrix[0].checks.len() - 1,
            mode,
            difficulty,
            i >= half_tests, // More concise match expression
        );
    }
    let adjusted_ranges: Vec<Vec<usize>> = ranges
        .iter()
        .map(|r| {
            let mut rand_num = thread_rng();
            let start = rand_num.gen_range(*r.start()..=*r.end());
            let full_cycle: Vec<usize> = (*r).clone().collect();
            full_cycle.iter().cycle().skip(start).take(full_cycle.len()).copied().collect()
        })
        .collect();

    print!("Generating the puzzle...");
    let mut puzzle = Puzzle::default();

    while puzzle.tests.len() < test_amount {
        puzzle = Puzzle {
            target_code: generate_random_puzzle_code(code_length as u32, min_digit, max_digit),
            tests: vec![]
        };
        let target_index = matrix.iter().position(|item| item.code == puzzle.target_code).unwrap();
        puzzle = puzzle_gen_algo(
            puzzle,
            &test_amount,
            target_index,
            &matrix,
            &adjusted_ranges,
            &vct_whole_range,
            &couplings
        );
    }
    puzzle
}

fn puzzle_gen_algo(
    mut puzzle: Puzzle,
    test_amount: &usize,
    target_index: usize,
    matrix: &Vec<TuringCodeEval>,
    adjusted_ranges: &Vec<Vec<usize>>,
    vct_whole_range: &Vec<bool>,
    couplings: &Vec<Vec<bool>>
) -> Puzzle {
    let pool: &Vec<usize> = &adjusted_ranges[puzzle.tests.len()];
    'pool_loop: for i in pool
        .iter()
        .filter(|i| matrix[target_index].checks[**i].1)
        .filter(|i| !vct_whole_range[**i])
    {
        if !puzzle.tests.iter().all(|&existing_test| !couplings[existing_test][*i])
            || puzzle.tests.iter().any(|a| matrix[0].checks[*a].0 == matrix[0].checks[*i].0) 
        {
            continue 'pool_loop;
        }
        if puzzle.tests.len() == *test_amount - 1 {
            puzzle.tests.push(*i);
            if is_unique_solution(&target_index, &puzzle.tests, &matrix) {
                println!("{} is a valid code for a test amount of {test_amount}.", puzzle.target_code);
                return puzzle;
            } else {
                puzzle.tests.pop();
                continue 'pool_loop;
            }
        } else if puzzle.tests.len() < test_amount - 1 {
            puzzle.tests.push(*i);
            let valid_solution_minimum: usize = (test_amount - puzzle.tests.len()) + 1;
            let mut solution_count = 0;
            'solution_counting: for (_, turing_code_result) in matrix.iter().enumerate() {
                if puzzle.tests
                    .iter()
                    .all(|&i| turing_code_result.checks.get(i).map_or(false, |&(_, b)| b)) 
                {
                    solution_count += 1;
                    if solution_count == valid_solution_minimum {
                        break 'solution_counting;
                    }
                }
            }
            if solution_count == valid_solution_minimum {
                puzzle = puzzle_gen_algo(
                    puzzle,
                    test_amount,
                    target_index,
                    &matrix,
                    &adjusted_ranges,
                    &vct_whole_range,
                    &couplings
                );
                break 'pool_loop;
            } else {
                puzzle.tests.pop();
                continue 'pool_loop;
            }
        }
    }
    puzzle.tests.sort();
    puzzle
}